# Generated by Django 5.1.3 on 2024-11-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.IntegerField(default=1, help_text='Cantidad de porciones'),
        ),
    ]
