# Generated by Django 5.1.3 on 2024-11-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_porciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['-created'], 'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
