# Generated by Django 4.2 on 2024-11-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='receta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='recetas.receta'),
        ),
    ]
