# Generated by Django 4.2 on 2024-11-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_tips_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='recetas.receta'),
        ),
    ]
