# Generated by Django 4.2 on 2024-11-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_alter_tips_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='receta',
        ),
        migrations.AddField(
            model_name='receta',
            name='tips',
            field=models.ManyToManyField(blank=True, to='recetas.tips'),
        ),
    ]
