# Generated by Django 4.2 on 2024-11-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_remove_tips_receta_receta_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='instrucciones',
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='recetas.receta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
