# Generated by Django 4.2 on 2024-11-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_remove_receta_instrucciones_paso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paso',
            options={'ordering': ['orden'], 'verbose_name': 'Paso', 'verbose_name_plural': 'Pasos'},
        ),
        migrations.RemoveField(
            model_name='receta',
            name='tips',
        ),
        migrations.AddField(
            model_name='receta',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tips',
            name='receta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='recetas.receta'),
        ),
    ]
