# Generated by Django 4.2 on 2024-11-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0011_alter_paso_options_remove_receta_tips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='instrucciones',
        ),
    ]
