# Generated by Django 5.1.3 on 2025-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0013_paciente_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='patient_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tips_photos/'),
        ),
    ]
