# Generated by Django 5.1.3 on 2025-04-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0014_tips_patient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_pacientes/'),
        ),
    ]
