# Generated by Django 5.1.3 on 2025-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0016_receta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
